---
title: "Analysis"
output: 
  html_document:
    toc: true
    toc_float: true
---
```{r include=FALSE}
library(tidyverse)
knitr::opts_chunk$set(
	echo = TRUE,
	warning = FALSE,
	fig.width = 8, 
  fig.height = 6,
  out.width = "90%"
)
options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)
scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
theme_set(theme_minimal() + theme(legend.position = "bottom",plot.title = element_text(face = "bold")))
```


```{r}
data_hist = 

 
  read_csv("data/NYPD_Shooting_Incident_Data_Clean.csv") %>%
  mutate(
    statistical_murder_flag = as.character(statistical_murder_flag),
    statistical_murder_flag = recode(statistical_murder_flag, "FALSE" = "survived","TRUE" = "murdered")
  )

```



##2010-2020 total shooting incident trends by year
```{r}
year_plot = 
  data_hist %>% 
  filter(year >= 2010
         ) %>% 
  group_by (year, statistical_murder_flag) %>%
  mutate(n = n()) %>% 
  ggplot(aes(x = year, y = n, color = statistical_murder_flag))  + scale_x_continuous(breaks = seq(2010, 2020, by = 1)) +
  geom_point() + geom_line()+
  #facet_grid (~statistical_murder_flag)
  labs(x = "Year",
       y = "Total incident",
       title = "Shooting Incident Trend By Year"
       )

year_plot
```





##2010-2020 total shooting incident by victim’s race

```{r}
vic_race_plot = 
  data_hist %>%
  filter(year >= 2010,
         vic_race %in% c("black","white hispanic","black hispanic","white","asian / pacific islander","white")) %>% 
  group_by(year,vic_race) %>%
  mutate(n = n()) %>%
  ggplot(aes(x = year, y = n, fill = vic_race)) + 
  geom_bar(width = 0.8, stat = "identity")+
  

  labs(x = "Year",
       y = "Total incident",
       title = "Shooting Incident Trend By Victim’s Race "
       )

vic_race_plot
```



##2010-2020 total shooting incident by victim’s sex
```{r}
vic_sex_plot = 
  data_hist %>% 
  filter(year >= 2010,
         vic_sex != "unknown") %>% 
  group_by(year, vic_sex) %>%
  mutate(n = n()) %>% 
  ggplot(aes(x = year, y = n, color = vic_sex)) + 
  geom_point() + geom_line() +
  labs(x = "Year",
       y = "Total incident",
       title = "Shooting Incident Trend By Victim’s Sex"
       )

vic_sex_plot
```

##2010-2020 totalshooting incident by victim’s age group
```{r}
vic_age_plot = 
  data_hist %>% 
  filter(year >= 2010,
         vic_age_group != "NA",
         vic_age_group != "UNKNOWN"
         ) %>% 
  group_by(vic_age_group) %>%
  mutate(n = n()) %>% 
  ggplot(aes(x = boro, group = n, fill = vic_age_group)) + 
  geom_bar(position = "dodge") +
  labs(x = "Borough",
       y = "Total incident",
       title = "Shooting Incident Trend By victim’s Age Group"
       )
  
vic_age_plot
```

##2010-2020 total shooting incident by boro
```{r}
boro_plot = 
  data_hist %>% 
  filter(year >= 2010) %>% 
  group_by(boro) %>%
  mutate(n = n()) %>% 
  ggplot(aes(x = boro, group = n)) + 
  geom_bar(position = "dodge") +
  labs(x = "Borough",
       y = "Total incident",
       title = "Shooting Incident By Borough"
       )

boro_plot
```

##2010-2020 total shooting incident by hour in a day
```{r}
incident_by_hour =
  data_hist %>%
  filter(year >= 2010) %>% 
  group_by(hour) %>%
  mutate(n = n()) %>% 
  ggplot(aes(x = hour, group = n)) + 
  geom_bar(position = "dodge") +
  facet_grid(rows = vars(boro)) +
  labs(x = "Hour",
       y = "Total incident",
       title = "Shooting Incident Trend By Hour In Day"
       )
  
incident_by_hour
```


##2010-2020 total shooting incident by jurisdiction_code
```{r}
jurisdiction_code =
  data_hist %>%
  filter(year > 2010) %>% 
  group_by(jurisdiction_code) %>%
  mutate(n = n()) %>% 
  ggplot(aes(x = jurisdiction_code, group = n)) + 
  geom_bar(position = "dodge") +
  labs(x = "Location of the incident",
       y = "Total incident",
       title = "Shooting Incident By Location Of The Incident"
       )

  
jurisdiction_code
```
